---
title: "Complications"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(ggthemes)
theme_set(theme_classic())
library(plotly)
```



```{r, warning=FALSE, echo=FALSE}
load('./data/df_combine.Rdata')

df_complication <- df_combine %>% 
  mutate(retina = as.numeric(retina),
         skin = as.numeric(skin),
         vessel = as.numeric(vessel),
         nerve = as.numeric(nerve),
         kidney = as.numeric(kidney)) %>% 
  mutate(complications = retina + skin + vessel + nerve + kidney + depression) %>%
  mutate(complications = as.factor(complications))

```



```{r, warning=FALSE, message=FALSE, echo=FALSE}
plot_ret<-ggplotly(ggplot(df_complication, aes(x = dmage, y = retina, colour=dmage)) +
    geom_histogram(stat = "identity", width = .6) +
    labs(title="The complication of retina with diabetes age",
         x = "dmage") +
    theme(axis.title.x =  element_blank(),
          axis.text.x  =  element_blank(), 
          axis.title.y = element_text(face="bold", size=12),
          axis.text.y  = element_text(angle=0, vjust=0.5, size=10),
          legend.title = element_text(size=12, face="bold"),
          legend.text = element_text(size = 12, face = "bold"))+
    facet_wrap(~gender))

plot_ret
```



```{r, warning=FALSE, message=FALSE, echo=FALSE, collapse = TRUE}

plot_skin<-ggplotly(ggplot(df_complication, aes(x = dmage, y = skin, colour=dmage)) +
    geom_histogram(stat = "identity", width = .6) +
    labs(title="The complication of Skin with diabetes age",
         x = "dmage") +
    theme(axis.title.x =  element_blank(),
          axis.text.x  =  element_blank(), 
          axis.title.y = element_text(face="bold", size=12),
          axis.text.y  = element_text(angle=0, vjust=0.5, size=10),
          legend.title = element_text(size=12, face="bold"),
          legend.text = element_text(size = 12, face = "bold"))+
    facet_wrap(~gender))

plot_skin


```


```{r, warning=FALSE, message=FALSE, echo=FALSE}
plot_vess<-ggplotly(ggplot(df_complication, aes(x = dmage, y = vessel, colour=dmage)) +
    geom_histogram(stat = "identity", width = .6) +
    labs(title="The complication of vessel with diabetes age",
         x = "dmage") +
    theme(axis.title.x =  element_blank(),
          axis.text.x  =  element_blank(), 
          axis.title.y = element_text(face="bold", size=12),
          axis.text.y  = element_text(angle=0, vjust=0.5, size=10),
          legend.title = element_text(size=12, face="bold"),
          legend.text = element_text(size = 12, face = "bold"))+
          facet_wrap(~gender))

plot_vess
```


```{r, warning=FALSE, message=FALSE, echo=FALSE}
plot_nerve<-ggplotly(ggplot(df_complication, aes(x = dmage, y = nerve, colour=dmage)) +
    geom_histogram(stat = "identity", width = .6) +
    labs(title="The complication of Nerve with diabetes age",
         x = "dmage") +
    theme(axis.title.x =  element_blank(),
          axis.text.x  =  element_blank(), 
          axis.title.y = element_text(face="bold", size=12),
          axis.text.y  = element_text(angle=0, vjust=0.5, size=10),
          legend.title = element_text(size=12, face="bold"),
          legend.text = element_text(size = 12, face = "bold"))+
          facet_wrap(~gender))

plot_nerve
```


```{r, warning=FALSE, message=FALSE, echo=FALSE}

plot_kidney<-ggplotly(ggplot(df_complication, aes(x = dmage, y = kidney, colour=dmage)) +
    geom_histogram(stat = "identity", width = .6) +
    labs(title="The complication of kidney with diabetes age",
         x = "dmage") +
    theme(axis.title.x =  element_blank(),
          axis.text.x  =  element_blank(), 
          axis.title.y = element_text(face="bold", size=12),
          axis.text.y  = element_text(angle=0, vjust=0.5, size=10),
          legend.title = element_text(size=12, face="bold"),
          legend.text = element_text(size = 12, face = "bold"))+
          facet_wrap(~gender))

plot_kidney
```


```{r, warning=FALSE, message=FALSE, echo=FALSE}
plot_depress<-ggplotly(ggplot(df_complication, aes(x = dmage, y =depression, colour=dmage)) +
    geom_histogram(stat = "identity", width = .6) +
    labs(title="The complication of Depression with diabetes age",
         x = "dmage") +
    theme(axis.title.x =  element_blank(),
          axis.text.x  =  element_blank(), 
          axis.title.y = element_text(face="bold", size=12),
          axis.text.y  = element_text(angle=0, vjust=0.5, size=10),
          legend.title = element_text(size=12, face="bold"),
          legend.text = element_text(size = 12, face = "bold"))+
    facet_wrap(~gender))

plot_depress
```




```{r, warning=FALSE, message=FALSE, echo=FALSE}
levels(df_complication$complications) <- list(none=0,one=1,more_than_two=c(2:6))
freqtable <- table(df_complication$complications)
df_com<- as.data.frame.table(freqtable) %>% 
  rename(complications = Var1,
         Frequence = Freq)
knitr::kable(df_com)

plot_com2<-ggplotly(ggplot(df_com, aes(x = complications, y = Frequence, fill=complications)) +
    geom_histogram(stat = "identity", width = .6) +
    labs(title="The Frequency of complications",
          x = "How many complications for diabetes patients",
           y = "Frequency") +
    theme(axis.title.x =  element_blank(),
          axis.text.x  =  element_blank(), 
          axis.title.y = element_text(face="bold", size=12),
          axis.text.y  = element_text(angle=0, vjust=0.5, size=10),
          legend.title = element_text(size=12, face="bold"),
          legend.text = element_text(size = 12, face = "bold")))
plot_com2


```

```{r}
ggplot(df_complication, aes(x = complications, y = dmage, hue = gender)) + 
  geom_violin(aes(fill = gender), color = "blue", alpha = .5) + 
  stat_summary(fun.y = median, geom = "point", color = "blue", size = 4)

```


