---
title: "exercise"
author: "Rui Huang"
date: "November 14, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(survminer)
library(survival)
library(plotly)
library(GGally)
library(tmap)
library(rgdal)
library(maptools)
library(rgeos)
```

### Cleaning data and rename variables

```{r}
load('./dm.Rdata')
df_raw = dm_base %>%   
  rename(subject_id = JiBenCID,  
         weight = tizhong,  
         height = ShenGao,  
         exercise_time = xiuxiansj) %>%   
  mutate(gender = ifelse(xingbie == 1, "Male", "Female"),  
         tb = ifelse(censer == 1, "No", "Yes"),  
         exercise = as.factor(xiuxiantl)) %>%   
  select(-xingbie, -censer, -xiuxiantl) %>%   
  janitor::clean_names()  
  
levels(df_raw$exercise) <- list("Mild" = 1,  "Medium" = 2,'heavy'=c(3,4))
```


### Combine data

```{r}
df_combine = dm_base %>% 
  rename(
    subject_id = JiBenCID,
    glu_average = fastglu, 
    weight_initial = tizhong_1st, 
    weight_average = tizhong, 
    height = ShenGao, 
    glu_initial = kfxt_1st,
    gender = xingbie,
    district = GuanLiQX,
    sys_pressure = Sbp,
    dia_pressure = Dbp,
    exercise_time = xiuxiansj,
    exercise = xiuxiantl,
    drug_insulin = insulin,
    drug_oral_sulfo = sulfonylurea,
    drug_oral_biguanide = biguanide,
    drug_oral_glu = glu_inhib,
    retina = reti, 
    skin = derm, 
    vessel = vesl, 
    nerve = neur,
    kidney = neph, 
    depression = depress,
    dmtime = quezhensj,
    birthyear  = birth_year,
    birthmon = birth_mon,
    dmdatayear = rucu_year,
    dmdatamon = rucu_mon,
    dmdataage = rucuage) %>% 
  mutate(
    bmi_initial = weight_initial/(height/100)^2, 
    bmi_average = weight_average/(height/100)^2, 
    bmi_change = bmi_average - bmi_initial,
    glu_change = glu_average - glu_initial,
    tb = ifelse(censer == 1, "No", "Yes"),
    exercise = as.factor(exercise),
    drug_oral = case_when(drug_oral_biguanide == 0 & drug_oral_biguanide == 0 &     drug_oral_glu == 0 ~0, TRUE ~ 1),
    drug = case_when(drug_oral == 0 & drug_insulin ==0 ~ 0,TRUE ~ 1),
    retina = as.numeric(retina),
    skin = as.numeric(skin),
    vessel = as.numeric(vessel),
    nerve = as.numeric(nerve),
    kidney = as.numeric(kidney),
    complications = retina + skin + vessel + nerve + kidney + depression,
    complications = as.factor(complications)
  )


levels(df_combine$complications) <- list(none=0,one=1,more_than_two=c(2,6))
levels(df_combine$exercise) <- list('1' = 1,  '2' = 2, '3' = c(3,4))
```

Compare male and female mean for exercise by t.test

```{r}
male_exercise = df_combine %>% 
  filter(gender == 1) %>% 
  mutate(exercise = as.numeric(exercise))
    
female_exercise = df_combine %>% 
  filter(gender == 2) %>% 
  mutate(exercise = as.numeric(exercise))

var.test(male_exercise$exercise,female_exercise$exercise, alternative = "two.sided")

t.test(male_exercise$exercise,female_exercise$exercise, var.equal=FALSE, paired=FALSE) 
```

Compare male and female mean for exercise_time by t.test

```{r}
var.test(male_exercise$exercise_time,female_exercise$exercise_time, alternative = "two.sided")

t.test(male_exercise$exercise_time,female_exercise$exercise_time, var.equal=FALSE, paired=FALSE) 
```

Compare male and female mean for exercise_time*exercise by t.test

```{r}
male_exercise = male_exercise %>% mutate(total_exercise = exercise * exercise_time)
female_exercise = female_exercise %>% mutate(total_exercise = exercise * exercise_time)
var.test(male_exercise$total_exercise,female_exercise$total_exercise, alternative = "two.sided")
t.test(male_exercise$total_exercise,female_exercise$total_exercise, var.equal=FALSE, paired=FALSE) 
```


### Incidence

```{r}
df_exercise = df_combine %>% 
  mutate(exercise = as.numeric(exercise),
         total_exercise = exercise * exercise_time,
         gender = as.factor(gender))
```


```{r}
df_incidence  <- df_exercise %>% 
  mutate(tb = fct_recode(tb, '1'= 'Yes', '0'='No')) %>% 
  mutate(tb=as.character(tb),
         tb=as.numeric(tb)) %>% 
  group_by(total_exercise) %>% 
  summarise(tb_sum = sum(tb),
           incidence = tb_sum/n()) %>% 
  ungroup()
```

### K-M plot for different exercise people

```{r}
df_exercise = df_exercise %>% 
  inner_join(df_incidence, by = "total_exercise")

df_exercise$survival = with(df_exercise, Surv(days, tb == "Yes"))

km <- survfit(survival ~ 1, data = df_exercise, conf.type = "log-log")
km_by_exercise <- survfit(survival ~ exercise, data = df_exercise, conf.type = "log-log")

km_by_exercise_time <- survfit(survival ~ exercise_time, data = df_exercise, conf.type = "log-log")

plot_exercise_level <- GGally::ggsurv(km_by_exercise, main = "Kaplan-Meier Curve for getting TB of different exercise level")
plotly::ggplotly(plot_exercise_level)

plot_exercise_time <- GGally::ggsurv(km_by_exercise_time, main = "Kaplan-Meier Curve for getting TB of different exercise time")
plotly::ggplotly(plot_exercise_time)

```


### Show exercise difference between gender

```{r}
plot_exer = ggplot(data = df_exercise, aes(x = gender, y = total_exercise, color = gender)) +
  geom_boxplot()

ggplotly(plot_exer)

```



### map


```{r}
x = df_exercise %>% 
  filter(district != "") %>%
  group_by(district) %>% 
  summarise(exercise_sum = sum(total_exercise)) %>% 
  ungroup()

levels(x$district) <- list("Huangpu" = 310101, "Xuhui" = 310104, "Changning" = c(310105, 310106), "Putuo" = 310107, "Zhabei" = 310108, "Hongkou" = 310109, "Yangpu" = 310110, "Minhang" = 310112, "Baoshan" = 310113,  "Pudong" = c(310115, 310119), "Jiading" = 310114, "Jinshan" = 310116, "Songjiang" = 310117, "Qingpu" = 310118, "Fengxian" = 310120, "Chongming" = 310230)
```

```{r}
sh <- readOGR('./data/shanghai_shapefile/shang_dis_merged.shp',verbose = F)
##Translating and Adding two missing two districts
sh@data <- sh@data %>% 
  mutate(Name = as.factor(Name)) %>%
  mutate(Name = fct_recode(Name, Jiading = '嘉定区',
                           Fengxian = '奉贤区',
                           Baoshan = '宝山区',
                           Chongming = '崇明县',
                           Xuhui = '徐汇区',
                           Putuo ='普陀区',
                           Yangpu = '杨浦区',
                           Songjiang = '松江区',
                           Pudong='浦东新区',
                           Hongkou = '虹口区',
                           Jinshan = '金山区',
                           Changning = '长宁区',
                           Minhang = '闵行区',
                           Zhabei = '闸北区',
                           Qingpu = '青浦区', 
                           Huangpu = '黄浦区'))


```

```{r}
sh$exercise_sum <- x$exercise_sum

qtm(sh, fill = "exercise_sum")
```












