---
title: "The Association Between Tuberculosis and Type II Diabetes and Risk Factors in Shanghai, China"
author: "Rui Huang (rh2916), Hanbo Qiu (hq2163), Annie Yu (xy2404), Dana Zeng (dz2399), Coco Zou (xz2809)"
date: "November 8, 2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

**Import data:**

```{r}
load("dm.RData")
```

**apply data cleaning of variables including "Initial BMI", "BMI changed", "Initial fasting glucose"" and "Fasting glucose change":**

Rename some predictor variables to meaningful ones.

```{r}
df_hanbo = dm_base %>% 
  rename(
    glu_average = fastglu, weight_initial = tizhong_1st, weight_average = tizhong, height = ShenGao, glu_initial = kfxt_1st)
```

Create new variables "bmi_initial","bmi_average" "bmi_change" and "glu_change"

```{r}
df_hanbo = df_hanbo %>% 
  mutate(
    bmi_initial = weight_initial/(height/100)^2, 
    bmi_average = weight_average/(height/100)^2, 
    bmi_change = bmi_average - bmi_initial,
    glu_change = glu_average - glu_initial
  )
```

Rename outcome "censor" to "tb_infection" and inverse its value.

```{r}
df_hanbo = df_hanbo %>% 
  rename(
    tb_infection = censer) %>% 
  mutate(tb_infection = ifelse(tb_infection == 1, 0, 1))
```

Rename other variables:

```{r}
df_hanbo = df_hanbo %>% 
  rename(
    gender = xingbie,
    district = GuanLiQX,
    sys_pressure = Sbp,
    dia_pressure = Dbp
  )
```

